# Generated by Django 2.2 on 2021-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='desc',
            field=models.TextField(default='dummy desc for old entries'),
            preserve_default=False,
        ),
    ]
