# Generated by Django 2.2 on 2021-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0002_wish_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
