# Generated by Django 2.2 on 2021-07-16 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0004_wish_date_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_granted',
            field=models.DateTimeField(default=datetime.time(0, 0)),
        ),
    ]
