# Generated by Django 2.2 on 2021-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes_app', '0005_auto_20210716_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
